# Site Settings
title: "Quantum bit d.o.o."
name: "Quantum bit d.o.o."
description: "Quantum bit d.o.o. — website under development."
url: "https://quantum-bit.net"
baseurl: ""

# Build Settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# SEO
twitter:
  username: ""

# Site Author
author:
  name: "Quantum bit d.o.o."
  location: "Croatia"

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.gem"
  - "*.gemspec"
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .jekyll-cache
  - .sass-cache
  - _site
  - README.md
  - LICENSE

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/Zagreb

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
